# Generated by Django 4.2.2 on 2023-08-11 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headLine', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.FileField(default=None, max_length=250, null=True, upload_to='media_coverage/')),
            ],
        ),
    ]
