# Generated by Django 4.2.2 on 2023-08-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_coverage', '0003_achievements_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='date',
            field=models.CharField(max_length=15),
        ),
    ]
