# Generated by Django 4.2.2 on 2023-08-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='campaigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=2)),
                ('m_y', models.CharField(max_length=10)),
                ('heading', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.FileField(default=None, max_length=250, null=True, upload_to='camapigns/')),
            ],
        ),
    ]
