# Generated by Django 4.2.2 on 2023-08-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='innovation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_by', models.CharField(max_length=15)),
                ('heading', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=8)),
                ('image', models.FileField(default=None, max_length=250, null=True, upload_to='innovations/')),
            ],
        ),
    ]
